#!/usr/bin/env python

""" set_systeminfo

Code to update system settings brought together in one script

This code expects a particular kind of JSON object to be submitted to it,
that is equivalent to the one returned by get_system_settings.

"""

import sys

#
# !!! I'm using simplejson here for the sole reason that everything I wrote
# in the library assumes strings rather than unicode, and json by default
# always encodes using unicode... It would probably be better to fix the
# code itself to use unicode, but I cannot imagine anything but ascii being
# o.k. for the various system settings.!!!
#
import simplejson

from settings.system import *

data = sys.stdin.readlines()
"""
def setKeyValue(data, fields, value):
    element=data
    if not elem.has_key(fields[0]) :
        sys.stderr.write("Field '%s' not found\n" % fields[0])
        
"""
#
# convert from unicode to string
#
val = str(''.join(data))

struct = simplejson.loads(val)

exe=True
forced=False
for arg in sys.argv:
    if arg == '-n' :
        exe=False
    elif arg == '-f':
        forced=True
#    else:
#        try:
#            equalpos=arg.index('=')
#        except:
#            continue
#        
#        #
#        key=



errors, foundErrors = set_systeminfo(struct, exe, forced)
if not forced:
    errors={ 'success': not foundErrors, 'errors' : errors }
    print simplejson.dumps(errors, sort_keys=True, indent=4)
