#! /bin/sh
### BEGIN INIT INFO
# Provides:          dbus
# Required-Start:    procps
# Required-Stop: 
# Default-Start:     3
# Default-Stop:
# Short-Description: dbus daemon.
# Description:
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin

. /lib/lsb/init-functions

OPTS="--system --fork"
PID_FILE=/var/run/dbus/pid
DAEMON=/bin/dbus-daemon
NAME="dbus"

case "$1" in
  start)
	log_daemon_msg "Starting ${NAME}" ""
    exec 9>&1
    exec 1>/dev/null
	if start-stop-daemon --start --quiet --pidfile ${PID_FILE} --exec ${DAEMON} -- ${OPTS}; then
        exec 1>&9
	    log_end_msg 0
	else
        exec 1>&9
	    log_end_msg 1
	fi
	;;
  stop)
	log_daemon_msg "Stopping ${NAME}" ""
	if start-stop-daemon --stop --quiet --oknodo --retry=TERM/20/KILL/5 --pidfile ${PID_FILE}; then
	    log_end_msg 0
	else
	    log_end_msg 1
	fi
    rm -f ${PID_FILE} 
	;;
  *)
	echo "Usage: $0 start|stop" >&2
	exit 3
	;;
esac
