#!/bin/sh
### BEGIN INIT INFO
# Provides:          final5
# Required-Start:    watchdog
# Default-Start:     5
# Short-Description: patcher for products where level 5 is not implemented
### END INIT INFO
