#! /bin/sh
### BEGIN INIT INFO
# Provides:          firewall
# Required-Start:    net
# Required-Stop:
# Default-Start:     3 5 8
# Default-Stop:      0 1 6
# Short-Description: start the filewall
### END INIT INFO

umask 022

if test -f /etc/default/ssh; then
    . /etc/default/ssh
fi

. /lib/lsb/init-functions

if [ -n "$2" ]; then
    SSHD_OPTS="$SSHD_OPTS $2"
fi

startit()
{
    
    firewall start
}

stopit()
{
    firewall stop
}
export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  start)
	log_daemon_msg "Starting Firewall" ""
	if startit 
    then
	    log_end_msg 0
	else
	    log_end_msg 1
	fi
	;;
  stop)
	log_daemon_msg "Stopping Firewall" ""
	if stopit 
    then
	    log_end_msg 0
	else
	    log_end_msg 1
	fi
	;;

  restart)
	log_daemon_msg "Restarting filrewall" ""
    stopit
    startit
    log_end_msg 0
	;;

  *)
	log_action_msg "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit 0
