#! /bin/sh
### BEGIN INIT INFO
# Provides:          reboot final6
# Required-Start:    hwclock
# Required-Stop: 
# Default-Start:     6
# Default-Stop:
# Short-Description: Execute the reboot command.
# Description:
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin

. /lib/lsb/init-functions

do_reboot () {
	# Message should end with a newline since kFreeBSD may
	# print more stuff (see #323749)
	log_action_msg "Will now restart"
	reboot -d -f -i
}

case "$1" in
  start)
	do_reboot
	;;
  restart|reload|force-reload)
	echo "Error: argument '$1' not supported" >&2
	exit 3
	;;
  stop)
	;;
  *)
	echo "Usage: $0 start|stop" >&2
	exit 3
	;;
esac
