#!/usr/bin/env python
"""
    Client side of the gitadmd (part of the gitserver node).
    Used by Rim spec management script to create/delete branches on a 
    remote git repositorie.
    
"""
import os, sys
import getopt

def usage():
    print "usage : gitadm [-c branch parent] [-d branch] [-p path] [-s server] [-l]"
    sys.exit(1)

try:
    optlist, args = getopt.getopt(sys.argv[1:], 's:p:a:d:l')
except:
    usage()

Cmd=""
Server=""
Path=""
Branch=""
Parent=""

for opt, arg in optlist:
    if opt == '-a':
        if len(Cmd): usage()
        if(len(args)!=1): usage()
        Cmd="add"
        Branch=arg
        Parent=args[0]
    elif opt ==  '-d':
        branch=arg
        if len(Cmd): usage()
        Cmd="delete"
        Branch=arg
    elif opt ==  '-l':
        if len(Cmd): usage()
        Cmd="list"
    elif opt == "-s":
        if len(Server): usage()
        Server=arg
    elif opt == "-p":
        if len(Path): usage()
        Path=arg
    else:
        usage()

if not len(Cmd) or not len(Server) or not len(Path): usage()

cmdS='\n    "cmd":"%s"' % Cmd
pathS='\n    "path":"%s",' % Path
if len(Branch): branchS='\n    "branch":"%s",' % Branch
else: branchS=""
if len(Parent): parentS='\n    "parent":"%s",' % Parent
else: parentS=""

message="\n{%s%s%s%s\n}" % (pathS, branchS, parentS, cmdS)

import socket
import sys

# Create a TCP/IP socket
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

# Connect the socket to the port where the server is listening
server_address = (Server, 9419)
sock.connect(server_address)
            
try:
    
    # Send data
    sock.sendall(message)
    msg=""
    data = sock.recv(1024)
    while len(data):
        msg+=data
        data = sock.recv(1024)
except:
    sys.exit(1)

if len(msg):
    responce=eval(msg)
    if responce['status'] != "ok":
        print "%s" % responce['msg']
    elif Cmd=="list":
        for b in responce['branches']:
            print b
else:
    print "Unknow error!?"
sys.exit(0)
