#! /bin/bash
### BEGIN INIT INFO
# Provides:          postgres
# Required-Start:    rimpredb ntp
# Required-Stop:
# Default-Start:     3 5
# Default-Stop:      0 1 6
# Short-Description: Stub for postgresql when not on target (shouldbe be db)
### END INIT INFO
