#! /bin/bash
### BEGIN INIT INFO
# Provides:          rimpostinstall
# Required-Start:    procps
# Required-Stop:
# Default-Start:     3 5 8
# Default-Stop:      0 1 3 6
# Short-Description: Run all of the commands for handling the very firts boot
# Description:       These commands are found in the bom.xml.sh file and will only be
#                    be executed if the /firstboot file exists. 
### END INIT INFO
#
# Sole purpose of this script is to enable actions on first boot
# put prior to db being up and running.
# Namely - database copy on the first time coming up to a a new version from a previous running one.
#
PATH=/usr/sbin:/usr/bin:/sbin:/bin

. /lib/lsb/init-functions
. /sbin/rimFuncs
setNodeEnvironment

cd /soft/$version

if [ "$1" == start -a -f /dopost ]
then
    log_action_msg "Executing PostInstall functions"
    rm -f /dopost
    doPostInstall $rimBuildLabel
fi

case "$1" in
  start)
	;;
  restart)
	;;
  stop)
	;;
  *)
	echo "Usage: $0 start|stop|restart" >&2
	exit 3
	;;
esac
exit 0
